- name: Ruby | Checking installed version
  shell: ruby -v | grep -o "ruby {{ ruby_version }}"
  register: _installed
  ignore_errors: True

- block:
  - name: Ruby | Ensure tarball is Downloaded.
    get_url:
      url: "{{ ruby_url }}"
      dest: "{{ ruby_tmp_path }}.tar"

  - name: Ruby | Extract.
    command: tar -zxf "{{ ruby_tmp_path }}.tar"

  - name: Ruby | Make, configure, and install ruby.
    command: "{{ item }}"
    args:
      chdir: "{{ ruby_tmp_path }}"
    with_items:
      - ./configure
      - make
      - sudo make install
  when: _installed.rc == 1

- name: Ruby | Ensure downloaded tarball is removed.
  file:
    path: "{{ ruby_tmp_path }}.tar"
    state: absent

- name: Ruby | Ensure alternatives are updated.
  alternatives:
    name: 'ruby'
    link: '/usr/bin/ruby'
    path: '/usr/local/bin/ruby'
